"""Add auto_label_enabled and workflow_status to product

Revision ID: d45d019d51cf
Revises: 
Create Date: 2025-07-07 23:27:44.856732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd45d019d51cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label_image', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('auto_generated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('print_status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_label_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('workflow_status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('quality_check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_generated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tolerance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_check', schema=None) as batch_op:
        batch_op.drop_column('tolerance')
        batch_op.drop_column('auto_generated')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('workflow_status')
        batch_op.drop_column('auto_label_enabled')

    with op.batch_alter_table('label', schema=None) as batch_op:
        batch_op.drop_column('print_status')
        batch_op.drop_column('auto_generated')
        batch_op.drop_column('label_image')

    # ### end Alembic commands ###
